[[shades]]
name = "blue-light-filter"
start_time = 19:00:00
end_time = 06:00:00

[[shades]]
name = "night-light"
default = true
start_time = 06:00:00
end_time = 06:00:00
[shaders.config]
type = "red-green" # "red-green", "green-red", "blue-yellow"
strength = 1.0     # 0.0 - 1.0

